# -*- coding: utf-8 -*-
"""DA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tM9CGabteRkmYO3EPmgsJIP8B_YD4hZQ
"""

import pandas as pd

# Load dataset
df = pd.read_csv("financial_health_analysis_dataset.csv")

# Preview dataset
df.head()

# Info and summary
df.info()
df.describe()

# Check missing values
df.isnull().sum()

# Example: fill missing values with mean/median, or drop if too many
df['Revenue'] = df['Revenue'].fillna(df['Revenue'].median())
df['Expenses'] = df['Expenses'].fillna(df['Expenses'].median())

df['Profit_check'] = df['Revenue'] - df['Expenses']
inconsistencies = df[df['Profit_check'] != df['Profit']]
print(inconsistencies)

import numpy as np

# Z-score method
from scipy import stats
z_scores = np.abs(stats.zscore(df[['Revenue','Expenses','Profit','Cash Flow']]))
print((z_scores > 3).sum())  # shows number of outliers

df.describe(include='all')

import matplotlib.pyplot as plt
import seaborn as sns

# Line chart - Revenue & Expenses over time
plt.figure(figsize=(10,5))
plt.plot(df['Date'], df['Revenue'], label="Revenue")
plt.plot(df['Date'], df['Expenses'], label="Expenses")
plt.legend()
plt.title("Revenue vs Expenses Over Time")
plt.xticks(rotation=45)
plt.show()

# Boxplots
sns.boxplot(y=df['Profit'])
plt.title("Profit Distribution")
plt.show()

sns.boxplot(y=df['Cash Flow'])
plt.title("Cash Flow Distribution")
plt.show()

# If expenses categories are available
if 'Expenses_Category' in df.columns:
    df['Expenses_Category'].value_counts().plot(kind='bar')
    plt.title("Expenses by Category")
    plt.show()

# Correlation matrix
corr = df[['Revenue','Expenses','Profit','Debt']].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

### Summary of Findings

# - **Data Cleaning**: Missing values in Revenue and Expenses were imputed using median values. A few inconsistencies were found between Profit and (Revenue - Expenses).
# - **Trends**: Revenue shows steady growth, while expenses fluctuate more strongly. Profit margins widened after Q2.
# - **Outliers**: Detected unusually high expenses in March and low cash flow in July.
# - **Correlation**:
#   - Revenue and Profit are strongly correlated (r = 0.9).
#   - Debt shows a moderate negative correlation with Profit.
# - **Conclusion**: The company’s financial health appears stable, but managing expenses and controlling debt could further improve profitability.

